name: ticketing-project
services:
  app:
    container_name: ticketing-app-container
    image: eclipse-temurin:17-jdk-jammy
    platform: linux/amd64
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: sh -c "java -jar *[!plain].jar"
    ports:
      - "${SERVER_PORT}:8080"
    restart: always
    env_file:
      - .env
    depends_on: # app이 mysql 보다 늦게 실행되도록 설정
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      TOSS_PAYMENTS_SECRET_KEY: ${TOSS_PAYMENTS_SECRET_KEY}
      TOSS_SUCCESS_URL: ${TOSS_SUCCESS_URL}
      TOSS_FAIL_URL: ${TOSS_FAIL_URL}
      TOSS_BASE_URL: ${TOSS_BASE_URL}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_AUTHORIZATION_URI: ${GOOGLE_AUTHORIZATION_URI}

      GOOGLE_AUTHORIZED_REDIRECT_URI: ${GOOGLE_AUTHORIZED_REDIRECT_URI}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '4.0'
        reservations:
          memory: 8G
          cpus: '2.0'
      replicas: 1


  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck: # 완전히 준비될 때까지 대기
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 10

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok-container
    ports:
      - "${NGROK_PORT}:4040"
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: [ "http", "--url=${NGROK_DOMAIN}", "host.docker.internal:${SERVER_PORT}" ]
    depends_on:
      - app


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-container
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped


volumes:
  mysql_data:  # h2-data 대신 mysql_data로 변경