services:
  app:
    image: eclipse-temurin:17-jdk-jammy
    platform: linux/amd64
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: sh -c "java -jar *[!plain].jar"
    ports:
      - "8080:8080"
    restart: "no"
    depends_on: # app이 h2 보다 늦게 실행되도록 설정
      - h2
    environment:
      SPRING_DATASOURCE_URL:  jdbc:h2:tcp://h2:1521/test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
  h2:
    image: oscarfonts/h2:latest
    container_name: h2-database
    ports:
      - "1521:1521"
      - "8181:81"
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers -tcpPort 1521 -webAllowOthers -webPort 81 -ifNotExists -baseDir /opt/h2-data
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data: # 인메모리가 아닌 디스크에 영구 저장