@startuml

!theme plain
autonumber "<b>[00]"
title 결제 생성과 확정 동시성 문제 (MQ)

actor User as "사용자"

box "Application Server" #LightCyan
    participant Controller
    participant Service
    participant Client as "Toss API Client"
    participant Publisher
end box

participant TOSS as "Toss Payments API"
database DB

box "Message Queue" #LightYellow
    participant Exchange
    participant Queue
    participant Handler as "EventHandler"
end box


== 1. 결제 승인 ==
User -> Controller: 결제 승인 요청 (POST /api/payment/toss/confirm)
Controller -> Service: confirmPayment(request)
Service -> Client:  Toss에 최종 결제 승인 요청   **[S2S]**
Service -> Publisher: '결제 승인' 이벤트 발행  **[비동기 처리]**

Publisher -> Exchange: '결제 확정' 이벤트 전송
Exchange -> Queue: 메시지 라우팅
Queue -> Handler: 이벤트 수신
Handler -> DB: **결제 승인**


== 2. 결제 확정 ==
TOSS -> Controller: 웹훅 수신 (POST /api/webhook/payment)
Controller -> Service: 웹훅 처리 요청
Service -> Publisher: '결제 완료' 웹훅 이벤트 발행  **[비동기 처리]**

Publisher -> Exchange: 이벤트 전송
Exchange -> Queue: 메시지 라우팅
Queue -> Handler: 이벤트 수신
Handler -> DB: **결제 확정**

@enduml