spring:
  application:
    name: concert
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

toss:
  payments:
    test-secrete-api-key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"
    success-url: "http://localhost:8080/payment/success"
    fail-url: "http://localhost:8080/payment/fail"
    base-url: "https://api.tosspayments.com/v1/payments"



