spring:
  application:
    name: concert

  output:
    ansi:
      enabled: always

  profiles:
    active: test

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버로 변경

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}

  boot:
    admin:
      context-path: /admin
      client:
        url: "http://localhost:8080/admin"
        auto-registration: true
        instance:
          name: "Ticketing Application"
          service-url: "http://localhost:8080"


server:
  tomcat:
    threads:
      max: 200
      min-spare: 50
    accept-count: 200

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: concert

toss:
  payments:
    test-secret-api-key: ${TOSS_PAYMENTS_SECRET_KEY}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}
    base-url: ${TOSS_BASE_URL}

google:
  oauth2:
    authorized-redirect-uri: ${GOOGLE_AUTHORIZED_REDIRECT_URI}


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}