name: load-test
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
  
  grafana:
    image: grafana/grafana:11.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb


  k6:
    image: grafana/k6:latest
    user: root
    volumes:
      - ./load-tests/tests:/app/tests
      - ./load-tests/result:/app/results
      - ./load-tests:/app
    command: [ "run",
               "--out","web-dashboard=host=0.0.0.0",
               "--out","influxdb=http://influxdb:8086/k6",
               "--out","json=/app/results/result.json",
               "/app/tests/integration-load-test.js" ]
    ports:
      - "5665:5665"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - influxdb



volumes:
  influxdb:
  grafana:

  
